### ISSUE TITLE
Race condition receiving a window update and closing a stream

### ISSUE THREAD

**Issue by mxinden** [paritytech/yamux#110]
The following scenario reveals a race condition in the stream closing logic.

Imagine sender S sending multiple messages to receiver R with the latter expecting exactly as many messages as the former sent.

1. After sending multiple messages S calls [`poll_close`](https://github.com/paritytech/yamux/blob/develop/src/connection/stream.rs#L349) on the `Stream` eventually returning `Poll::Ready(Ok(()))`. At this point there are multiple pending messages in the channel between `Stream` and `Connection`. In addition, the last element in the channel between `Stream` and `Connection` is a `StreamCommand::CloseStream`.
2. With `poll_close` returning `Poll::Ready(Ok(()))` the user of the stream drops its reference, thus the overall reference count on the inner `Shared` drops to 1, with `Connection` holding the last reference.
3. `Connection::garbage_collect` is called. It iterates through all streams, finding the one mentioned above with a reference count of 1 and thus garbage collecting it, i.e. removing it from `Connection.streams`. Note: At this point there are still multiple messages pending in the channel between `Stream` and `Connection` as well as a final `StreamCommand::CloseStream` command.
4. Instead of sending out the above mentioned pending items S receives a window update message from R for the stream that S just closed. Given that S just garbage collected the stream, S will send a [stream reset](https://github.com/paritytech/yamux/blob/90720d796ef66b64f6453d8342c8f786ea5611ef/src/connection.rs#L784-L787) to R. Note, the items in the channel between the garbage collected `Stream` and the `Connection` are still pending.
5. R receives the stream reset and [marks the connection as closed](https://github.com/paritytech/yamux/blob/develop/src/connection.rs#L625). In the `AsyncRead` implementation `poll_read` finds `self.shared.buffer` to be empty. It then checks whether it [can expect to ever read more bytes](https://github.com/paritytech/yamux/blob/develop/src/connection/stream.rs#L293) from the stream, but given that it has been marked as closed, it will return `Poll::Ready(Ok(0)))`. The user on the receiving side interprets this as an EOF while still expecting more data. Note, at this point the previously pending items might still be pending in the channel on S, or might be on their way to R.

I can deterministically reproduce this error when applying the following diff to https://github.com/paritytech/yamux/pull/109/commits/df117583b708aae9a8e03c5668370093dc0dd345 and running `cargo bench`.

```diff
diff --git a/src/connection.rs b/src/connection.rs
index eb944f5..ad415ab 100644
--- a/src/connection.rs
+++ b/src/connection.rs
@@ -778,7 +780,11 @@ impl<T: AsyncRead + AsyncWrite + Unpin> Connection<T> {
                 w.wake()
             }
         } else if !is_finish {
-            log::debug!("{}/{}: window update for unknown stream, ignoring", self.id, stream_id);
+            log::debug!("{}/{}: window update for unknown stream", self.id, stream_id);
+            let mut header = Header::data(stream_id, 0);
+            header.rst();
+            return Action::Reset(Frame::new(header))
         }
```

I need to put more thoughts into a fix. For now I am just documenting my observation.

**Comment by mxinden** [comment]
Note, this race condition will only surface when sending window updates early (https://github.com/paritytech/yamux/pull/109/). When sending window updates on window exhaustion, the window update will arrive after the last data frame departed by definition as the latter caused the former. Thus data frames and stream resets won't be interleaved.

**Comment by romanb** [comment]
I edited the title just to make it clearer that this is not a bug in the current implementation but only relates to #109.

**Comment by romanb** [comment]
> I edited the title just to make it clearer that this is not a bug in the current implementation but only relates to #109.

Though, I think, when it comes to interoperability, it seems a different Yamux implementation may well send window updates earlier, thus causing this problem as well.

**Comment by mxinden** [comment]
An additional thing to note: The above race condition can not only be triggered by window update messages on garbage collected streams, but as well by data frames and pings on garbage collected streams.

Thus far I see the following ways forward:

- **Ignore** window updates, data frames and pings for unknown, possibly garbage collected, streams. This seems to be the least intrusive change.
- Today `AsyncRead::poll_close` on `Stream` returns `Poll::Ready(Ok(()))` as soon as the `StreamCommand::CloseStream` message has been sent into the channel to the `Connection`. Instead one could return `Poll::Ready(Ok(()))` from `AsyncRead::poll_close` on `Stream` only once `Connection` received the `StreamCommand::CloseStream` and send it on the socket.
- Introduce a **new state** `SendClosing` representing a stream in the process of sending out a `FIN` frame. While likely the most correct solution, trying to implement it quickly shows that it leads to a state _explosion_. Today, when receiving a `FIN` frame from the remote while already in `SendClosed` state, the stream is moved to `Closed`. When introducing the additional state `SendClosing` and receiving a `FIN` frame, one can not move to `Closed`, as that would not show that the own `FIN` frame is not yet send out, thus allowing the above race condition to happen.

- The above race condition is only possible due to the fact that information is shared through two non-inter-synchronized paths between `Stream` and `Connection`. The first path is through the `Mutex`-guarded `Shared` state. The second is through the command channel between `Stream` and `Connection`. To reduce the likely hood of the race condition to happen, one could **reduce the channel buffer size**. 
    ```diff
    diff --git a/src/connection.rs b/src/connection.rs
    index eb944f5..71f505b 100644
    --- a/src/connection.rs
    +++ b/src/connection.rs
    @@ -115,7 +115,7 @@ pub use stream::{Packet, State, Stream};
    ///
    /// Since each `mpsc::Sender` gets a guaranteed slot in a channel the
    /// actual upper bound is this value + number of clones.
    -const MAX_COMMAND_BACKLOG: usize = 32;
    +const MAX_COMMAND_BACKLOG: usize = 0;
    ```
    I am unable to reproduce the race condition with the change above. That said, I don't think it is a viable solution as it only reduces the probability for the race condition to occur.

**Comment by romanb** [comment]
> Ignore window updates, data frames and pings for unknown, possibly garbage collected, streams. This seems to be the least intrusive change.

I think this is the preferred option. It just needs to be documented clearly that this is because streams that have already been dropped may still have unprocessed `StreamCommand`s in the queue.

**Comment by mxinden** [comment]
<details>
  <summary>For the sake of completeness, here is the implementation for option 2, delaying `poll_close` to resolve.</summary>
  
  ```diff
diff --git a/src/connection.rs b/src/connection.rs
index eb944f5..89c2595 100644
--- a/src/connection.rs
+++ b/src/connection.rs
@@ -531,7 +531,14 @@ impl<T: AsyncRead + AsyncWrite + Unpin> Connection<T> {
                 header.fin();
                 if ack { header.ack() }
                 let frame = Frame::new(header);
-                self.socket.get_mut().send(&frame).await.or(Err(ConnectionError::Closed))?
+                self.socket.get_mut().send(&frame).await.or(Err(ConnectionError::Closed))?;
+                if let Some(stream) = self.streams.get(&id) {
+                    let mut shared = stream.shared();
+                    shared.update_state(self.id, id, State::SendClosed);
+                    if let Some(waker) = shared.writer.take() {
+                        waker.wake();
+                    }
+                }
             }
             None => {
                 // We only get to this point when `self.stream_receiver`
@@ -778,7 +785,10 @@ impl<T: AsyncRead + AsyncWrite + Unpin> Connection<T> {
                 w.wake()
             }
         } else if !is_finish {
-            log::debug!("{}/{}: window update for unknown stream, ignoring", self.id, stream_id);
+            log::debug!("{}/{}: window update for unknown stream", self.id, stream_id);
+            let mut header = Header::data(stream_id, 0);
+            header.rst();
+            return Action::Reset(Frame::new(header))
         }
 
         Action::None
diff --git a/src/connection/stream.rs b/src/connection/stream.rs
index aff6fc4..9d776d0 100644
--- a/src/connection/stream.rs
+++ b/src/connection/stream.rs
@@ -327,9 +327,14 @@ impl AsyncWrite for Stream {
     }
 
     fn poll_close(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<io::Result<()>> {
-        if self.state() == State::Closed {
+        if self.state() == State::Closed || self.state() == State::SendClosed {
             return Poll::Ready(Ok(()))
         }
+
+        if self.shared().send_closing {
+            return Poll::Pending;
+        }
+
         ready!(self.sender.poll_ready(cx).map_err(|_| self.write_zero_err())?);
         let ack = if self.flag == Flag::Ack {
             self.flag = Flag::None;
@@ -340,8 +345,12 @@ impl AsyncWrite for Stream {
         log::trace!("{}/{}: close", self.conn, self.id);
         let cmd = StreamCommand::CloseStream { id: self.id, ack };
         self.sender.start_send(cmd).map_err(|_| self.write_zero_err())?;
-        self.shared().update_state(self.conn, self.id, State::SendClosed);
-        Poll::Ready(Ok(()))
+
+        let mut shared = self.shared();
+        shared.send_closing = true;
+        shared.writer = Some(cx.waker().clone());
+
+        Poll::Pending
     }
 }
 
@@ -353,7 +362,8 @@ pub(crate) struct Shared {
     pub(crate) buffer: Chunks,
     pub(crate) reader: Option<Waker>,
     pub(crate) writer: Option<Waker>,
-    config: Arc<Config>
+    config: Arc<Config>,
+    send_closing: bool,
 }
 
 impl Shared {
@@ -365,7 +375,8 @@ impl Shared {
             buffer: Chunks::new(),
             reader: None,
             writer: None,
-            config
+            config,
+            send_closing: false,
         }
     }
```
</details>


> > Ignore window updates, data frames and pings for unknown, possibly garbage collected, streams. This seems to be the least intrusive change.
> 
> I think this is the preferred option. It just needs to be documented clearly that this is because streams that have already been dropped may still have unprocessed `StreamCommand`s in the queue and hence we do not want to interfere by sending a possibly interleaved reset.

Agreed. I will make https://github.com/paritytech/yamux/pull/109/ additionally ignore data frames and pings from unknown streams as well and make sure all cases are properly documented. Thanks for the input @romanb.
